# http://travis-ci.org/#!/graphite-project/ceres
language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -r test_requirements.txt --use-mirrors
    - python setup.py install
script:
    - nosetests
    - flake8 --max-line-length=100 --ignore=E111,E121 ceres.py tests/* bin/*
